type tEnumOptions = {
  [key: string]: string
}

export const educationList: tEnumOptions = {
  EDUCACAO_INFANTIL: 'Educação infantil',
  ENSINO_FUNDAMENTAL: 'Ensino Fundamental',
  ENSINO_MEDIO: 'Ensino Médio',
  ENSINO_SUPERIOR: 'Ensino Superior (Graduação)',
  POS_GRADUACAO: 'Pós-graduação',
  MESTRADO: 'Mestrado',
  DOUTORADO: 'Doutorado',
}

export const educationCalculationList: tEnumOptions = {
  ENSINO_FUNDAMENTAL: 'Fundamental Completo/Incompleto',
  ENSINO_MEDIO: 'Médio Completo / Incompleto',
  ENSINO_SUPERIOR: 'Superior Completo / Incompleto',
  POS_GRADUACAO: 'Pós-graduação',
  MESTRADO: 'Mestrado',
  DOUTORADO: 'Doutorado',
}

export const raceList: tEnumOptions = {
  AMARELO: 'Amarelo',
  BRANCO: 'Branco',
  PARDO: 'Pardo',
  INDIGENA: 'Indígena',
  PRETO: 'Preto',
  PREFIRO_NAO_RESPONDER: 'Prefiro não revelar',
}

export const disabledList: tEnumOptions = {
  DESLIGAMENTO_ABC: 'Desligamento da ABC',
  FALECIMENTO: 'Falecimento',
  TEMPO_CONTRATO_FINALIZADO: 'Tempo de contrato finalizado',
  SOLICITACAO_RESCISAO_CONTRATUAL: 'Solicitação de rescisão contratual',
}

export const programList = ['PARC', 'EPV', 'DDI', 'DCE']

type tListOptions = {
  [key: string]: string[]
}

export const roleList: tListOptions = {
  PARC: [
    'Diretor de Programa',
    'Diretor de Programa Adjunto',
    'Assessor de Direção',
    'Analista de Avaliação',
    'Analista de Dados',
    'Analista de Material Didático',
    'Analista de Formação do El e CA',
    'Coordenador de Implementação',
    'Coordenador Assistente',
    'Gestor de Projetos',
    'Auxiliar de Projetos',
    'Analista de Implementação',
  ],
  EPV: [
    'Diretor de Programa',
    'Diretor de Programa Adjunto',
    'Assessor de Direção',
    'Coordenador de Avaliação',
    'Analista de Avaliação',
    'Coordenador de Implementação',
    'Coordenador Assistente',
    'Auxiliar de Projetos',
    'Assistente Administrativo',
  ],
  DDI: [
    'Diretor',
    'Diretor Adjunto',
    'Coordenador Tecnologia e Informação',
    'Coordenador de Comunicação',
    'Coordenador Núcleo de Monitoramento',
    'Gerente de Gente e Gestão',
    'Gerente Administrativo Financeiro',
    'Analista Administrativo Financeiro',
    'Gestor de Projetos',
    'Assessor de Governança',
    'Assessor de Comunicação',
    'Assistente Administrativo',
  ],
  DCE: [
    'Diretor',
    'Assessor',
    'Coordenador de Articulação',
    'Coordenador do Núcleo',
    'Formação',
    'Coordenador do Núcleo de Avaliação',
  ],
}

export const genderList: tEnumOptions = {
  HOMEM_CIS: 'Homem Cis',
  HOMEM_TRANS: 'Homem Trans',
  MULHER_CIS: 'Mulher Cis',
  MULHER_TRANS: 'Mulher Trans',
  TRAVESTI: 'Travesti',
  NAO_BINARIO: 'Não Binário',
  OUTRO: 'Outro',
  PREFIRO_NAO_RESPONDER: 'Prefiro não responder',
}

export const statusContractList = [
  'Possuem contratos',
  'Não possuem contratos',
  'Contratos em vigência',
]

export const servicesList: tEnumOptions = {
  AGUA: 'Água',
  ALIMENTACAO: 'Alimentação',
  AR_CONDICIONADO: 'Ar condicionado',
  ASSESSORIA: 'Assessoria',
  AUDITORIA_EXTERNA: 'Auditoria Externa',
  BUFFET: 'Buffet',
  COMPRAS_E_SUPRIMENTOS: 'Compras e suprimentos',
  CONSULTORIA: 'Consultoria',
  CONTABEIS: 'Contábeis',
  DEDETIZACAO: 'Dedetização',
  ELETRICO: 'Elétrico',
  EMISSAO_DE_PASSAGEM: 'Emissão de Passagem',
  ENERGIA: 'Energia',
  ENTREGA: 'Entrega',
  ESGOTO: 'Esgoto',
  GRAFICA: 'Gráfica',
  HIDRAULICO: 'Hidráulico',
  INFORMATICA: 'Informática',
  INTERNET: 'Internet',
  JURIDICO: 'Jurídico',
  LAVAGEM: 'Lavagem',
  LIMPEZA: 'Limpeza',
  LOCATICIOS: 'Locatícios',
  MANUTENCAO: 'Manutenção',
  MARCENARIA: 'Marcenaria',
  MATERIAL_DE_CONSUMO: 'Material de Consumo',
  MATERIAL_DE_INFORMATICA: 'Material de Informática',
  MATERIAL_DE_LIMPEZA: 'Material de Limpeza',
  MATERIAL_EXPEDIENTE: 'Material Expediente',
  OBRAS: 'Obras',
  ORGANIZACAO_DE_EVENTOS: 'Organização de eventos',
  PINTURA: 'Pintura',
  PRODUCAO: 'Produção',
  RESERVA_DE_HOSPEDAGEM: 'Reserva de Hospedagem',
  SEGURANCA: 'Segurança',
  SERVICOS_ADMINISTRATIVOS: 'Serviços Administrativos',
  TRASPORTE: 'Transporte',
  VIDRACARIA: 'Vidraçaria',
}

export const pixKeyTypes: tEnumOptions = {
  CPF: 'CPF',
  CNPJ: 'CNPJ',
  EMAIL: 'Email',
  CELLPHONE: 'Telefone',
  ALEATORY_KEY: 'Chave aleatória',
}

export const foodCategory: tEnumOptions = {
  ONIVORO: 'Onívoro (a)',
  VEGANO: 'Vegano (a)',
  VEGETARIANO: 'Vegetariano (a)',
  PESCETARIANO: 'Pescetariano (a)',
  PREFIRO_NAO_RESPONDER: 'Prefiro não responder',
}

export const statusList: tEnumOptions = {
  PRE_CADASTRO: 'Pré Cadastrado',
  CADASTRO_COMPLETO: 'Cadastrado',
}

export const statusBudgetList: tEnumOptions = {
  APROVADO: 'Aprovado',
  EM_CALIBRACAO: 'Em Calibração',
  RASCUNHO: 'Rascunho',
}

export const budgetPlanStatus: tEnumOptions = {
  APROVADO: 'APROVADO',
  EM_CALIBRACAO: 'EM_CALIBRACAO',
  RASCUNHO: 'RASCUNHO',
}

export const costCenterPARCList: tEnumOptions = {
  AVALIACAO_EXTERNA: 'Avaliação Externa',
  PESSOAL: 'Pessoal',
  LOGISTICA: 'Logística',
  EVENTOS: 'Eventos',
  ADMINISTRACAO: 'Administração',
}

export const costCenterEPVList: tEnumOptions = {
  CONSULTORIA: 'Consultoria',
  PESSOAL: 'Pessoal',
  COMUNICACAO: 'Comunicação',
  LOGISTICA: 'Logística',
  AVALIACAO_EXTERNA: 'Avaliação Externa',
  PRODUÇÃO_DE_CONTEUDO: 'Produção De Conteúdo',
  ADMINISTRACAO: 'Administração',
}

export const costCenterSubCatOption: tEnumOptions = {
  INSTITUCIONAL: 'Institucional',
  REDE: 'Rede',
}

export const CostCenterType: tEnumOptions = {
  'A PAGAR': 'A PAGAR',
  'A RECEBER': 'A RECEBER',
}

export const SubCategoryReleaseType: tEnumOptions = {
  IPCA: 'IPCA',
  CAED: 'CAED',
  DESPESAS_PESSOAIS: 'DESPESAS PESSOAIS',
  DESPESAS_LOGISTICAS: 'DESPESAS LOGISTICAS',
}

export enum bankAccounts {
  '001' = '001 - Banco do Brasil S.A.',
  '003' = '003 - Banco da Amazônia S.A.',
  '0004' = '004 - Banco do Nordeste do Brasil S.A.',
  '0007' = '007 - Banco Nacional de Desenvolvimento Econômico e Social – BNDES',
  '0010' = '010 - CREDICOAMO CREDITO RURAL COOPERATIVA',
  '0011' = '011 - CREDIT SUISSE HEDGING-GRIFFO CORRETORA DE VALORES S.A',
  '0012' = '012 - Banco Inbursa S.A.',
  '0014' = '014 - State Street Brasil S.A. – Banco Comercial',
  '0015' = '015 - UBS Brasil Corretora de Câmbio, Títulos e Valores Mobiliários S.A.',
  '0016' = '016 - COOPERATIVA DE CRÉDITO MÚTUO DOS DESPACHANTES DE TRÂNSITO DE SANTA CATARINA E RI',
  '0017' = '017 - BNY Mellon Banco S.A.',
  '0018' = '018 - Banco Tricury S.A.',
  '0021' = '021 - BANESTES S.A. Banco do Estado do Espírito Santo',
  '0024' = '024 - Banco BANDEPE S.A.',
  '0025' = '025 - Banco Alfa S.A.',
  '0029' = '029 - Banco Itaú Consignado S.A.',
  '0033' = '033 - Banco Santander (Brasil) S.A.',
  '0036' = '036 - Banco Bradesco BBI S.A.',
  '0037' = '037 - Banco do Estado do Pará S.A.',
  '0040' = '040 - Banco Cargill S.A.',
  '0041' = '041 - Banco do Estado do Rio Grande do Sul S.A.',
  '0047' = '047 - Banco do Estado de Sergipe S.A.',
  '0060' = '060 - Confidence Corretora de Câmbio S.A.',
  '0062' = '062 - Hipercard Banco Múltiplo S.A.',
  '0063' = '063 - Banco Bradescard S.A.',
  '0064' = '064 - Goldman Sachs do Brasil Banco Múltiplo S.A.',
  '0065' = '065 - Banco Andbank (Brasil) S.A.',
  '0066' = '066 - Banco Morgan Stanley S.A.',
  '0069' = '069 - Banco Crefisa S.A.',
  '0070' = '070 - BRB – Banco de Brasília S.A.',
  '0074' = '074 - Banco J. Safra S.A.',
  '0075' = '075 - Banco ABN AMRO S.A.',
  '0076' = '076 - Banco KDB S.A.',
  '0077' = '077 - Banco Inter S.A.',
  '0078' = '078 - Haitong Banco de Investimento do Brasil S.A.',
  '0079' = '079 - Banco Original do Agronegócio S.A.',
  '0080' = '080 - B&T CORRETORA DE CAMBIO LTDA.',
  '0081' = '081 - BancoSeguro S.A.',
  '0082' = '082 - Banco Topázio S.A.',
  '0083' = '083 - Banco da China Brasil S.A.',
  '0084' = '084 - Uniprime Norte do Paraná – Coop de Economia e Crédito Mútuo dos Médicos',
  '0085' = '085 - Cooperativa Central de Crédito – AILOS',
  '0089' = '089 - CREDISAN COOPERATIVA DE CRÉDITO',
  '0091' = '091 - CENTRAL DE COOPERATIVAS DE ECONOMIA E CRÉDITO MÚTUO DO ESTADO DO RIO GRANDE DO S',
  '0092' = '092 - Brickell S.A. Crédito',
  '0093' = '093 - PÓLOCRED SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORT',
  '0094' = '094 - Banco Finaxis S.A.',
  '0095' = '095 - Travelex Banco de Câmbio S.A.',
  '0096' = '096 - Banco B3 S.A.',
  '0097' = '097 - Cooperativa Central de Crédito Noroeste Brasileiro Ltda.',
  '0098' = '098 - Credialiança Cooperativa de Crédito Rural',
  '0099' = '099 - UNIPRIME CENTRAL – CENTRAL INTERESTADUAL DE COOPERATIVAS DE CREDITO LTDA.',
  '0100' = '100 - Planner Corretora de Valores S.A.',
  '0101' = '101 - RENASCENCA DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA',
  '0102' = '102 - XP INVESTIMENTOS CORRETORA DE CÂMBIO,TÍTULOS E VALORES MOBILIÁRIOS S/A',
  '0104' = '104 - Caixa Econômica Federal',
  '0105' = '105 - Lecca Crédito, Financiamento e Investimento S/A',
  '0107' = '107 - Banco BOCOM BBM S.A.',
  '0108' = '108 - PORTOCRED S.A. – CRÉDITO, FINANCIAMENTO E INVESTIMENTO',
  '0111' = '111 - OLIVEIRA TRUST DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIARIOS S.A.',
  '0113' = '113 - Magliano S.A. Corretora de Cambio e Valores Mobiliarios',
  '0114' = '114 - Central Cooperativa de Crédito no Estado do Espírito Santo – CECOOP',
  '0117' = '117 - ADVANCED CORRETORA DE CÂMBIO LTDA',
  '0119' = '119 - Banco Western Union do Brasil S.A.',
  '0120' = '120 - Banco Rodobens S.A.',
  '0121' = '121 - Banco Agibank S.A.',
  '0122' = '122 - Banco Bradesco BERJ S.A.',
  '0124' = '124 - Banco Woori Bank do Brasil S.A.',
  '0125' = '125 - Plural S.A. – Banco Múltiplo',
  '0126' = '126 - BR Partners Banco de Investimento S.A.',
  '0127' = '127 - Codepe Corretora de Valores e Câmbio S.A.',
  '0128' = '128 - MS Bank S.A. Banco de Câmbio',
  '0129' = '129 - UBS Brasil Banco de Investimento S.A.',
  '0130' = '130 - CARUANA S.A. – SOCIEDADE DE CRÉDITO, FINANCIAMENTO E INVESTIMENTO',
  '0131' = '131 - TULLETT PREBON BRASIL CORRETORA DE VALORES E CÂMBIO LTDA',
  '0132' = '132 - ICBC do Brasil Banco Múltiplo S.A.',
  '0133' = '133 - CONFEDERAÇÃO NACIONAL DAS COOPERATIVAS CENTRAIS DE CRÉDITO E ECONOMIA FAMILIAR E',
  '0134' = '134 - BGC LIQUIDEZ DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA',
  '0136' = '136 - CONFEDERAÇÃO NACIONAL DAS COOPERATIVAS CENTRAIS UNICRED LTDA. – UNICRED DO BRASI',
  '0138' = '138 - Get Money Corretora de Câmbio S.A.',
  '0139' = '139 - Intesa Sanpaolo Brasil S.A. – Banco Múltiplo',
  '0140' = '140 - Easynvest – Título Corretora de Valores SA',
  '0142' = '142 - Broker Brasil Corretora de Câmbio Ltda.',
  '0143' = '143 - Treviso Corretora de Câmbio S.A.',
  '0144' = '144 - BEXS Banco de Câmbio S.A.',
  '0145' = '145 - LEVYCAM – CORRETORA DE CAMBIO E VALORES LTDA.',
  '0146' = '146 - GUITTA CORRETORA DE CAMBIO LTDA.',
  '0149' = '149 - Facta Financeira S.A. – Crédito Financiamento e Investimento',
  '0157' = '157 - ICAP do Brasil Corretora de Títulos e Valores Mobiliários Ltda.',
  '0159' = '159 - Casa do Crédito S.A. Sociedade de Crédito ao Microempreendedor',
  '0163' = '163 - Commerzbank Brasil S.A. – Banco Múltiplo',
  '0169' = '169 - Banco Olé Bonsucesso Consignado S.A.',
  '0173' = '173 - BRL Trust Distribuidora de Títulos e Valores Mobiliários S.A.',
  '0174' = '174 - PERNAMBUCANAS FINANCIADORA S.A. – CRÉDITO, FINANCIAMENTO E INVESTIMENTO',
  '0177' = '177 - Guide Investimentos S.A. Corretora de Valores',
  '0180' = '180 - CM CAPITAL MARKETS CORRETORA DE CÂMBIO, TÍTULOS E VALORES MOBILIÁRIOS LTDA',
  '0183' = '183 - SOCRED S.A. – SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO P',
  '0184' = '184 - Banco Itaú BBA S.A.',
  '0188' = '188 - ATIVA INVESTIMENTOS S.A. CORRETORA DE TÍTULOS, CÂMBIO E VALORES',
  '0189' = '189 - HS FINANCEIRA S/A CREDITO, FINANCIAMENTO E INVESTIMENTOS',
  '0190' = '190 - SERVICOOP – COOPERATIVA DE CRÉDITO DOS SERVIDORES PÚBLICOS ESTADUAIS DO RIO GRAN',
  '0191' = '191 - Nova Futura Corretora de Títulos e Valores Mobiliários Ltda.',
  '0194' = '194 - PARMETAL DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA',
  '0196' = '196 - FAIR CORRETORA DE CAMBIO S.A.',
  '0197' = '197 - Stone Pagamentos S.A.',
  '0208' = '208 - Banco BTG Pactual S.A.',
  '0212' = '212 - Banco Original S.A.',
  '0213' = '213 - Banco Arbi S.A.',
  '0217' = '217 - Banco John Deere S.A.',
  '0218' = '218 - Banco BS2 S.A.',
  '0222' = '222 - Banco Credit Agricole Brasil S.A.',
  '0224' = '224 - Banco Fibra S.A.',
  '0233' = '233 - Banco Cifra S.A.',
  '0237' = '237 - Banco Bradesco S.A.',
  '0241' = '241 - Banco Clássico S.A.',
  '0243' = '243 - Banco Máxima S.A.',
  '0246' = '246 - Banco ABC Brasil S.A.',
  '0249' = '249 - Banco Investcred Unibanco S.A.',
  '0250' = '250 - BCV – Banco de Crédito e Varejo S.A.',
  '0253' = '253 - Bexs Corretora de Câmbio S/A',
  '0254' = '254 - Paraná Banco S.A.',
  '0259' = '259 - MONEYCORP BANCO DE CÂMBIO S.A.',
  '0260' = '260 - NU Pagamentos S.A. – Nubank',
  '0265' = '265 - Banco Fator S.A.',
  '0266' = '266 - Banco Cédula S.A.',
  '0268' = '268 - BARI COMPANHIA HIPOTECÁRIA',
  '0269' = '269 - HSBC Brasil S.A. – Banco de Investimento',
  '0270' = '270 - Sagitur Corretora de Câmbio Ltda.',
  '0271' = '271 - IB Corretora de Câmbio, Títulos e Valores Mobiliários S.A.',
  '0272' = '272 - AGK CORRETORA DE CAMBIO S.A.',
  '0273' = '273 - Cooperativa de Crédito Rural de São Miguel do Oeste – Sulcredi/São Miguel',
  '0274' = '274 - MONEY PLUS SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E A EMPRESA DE PEQUENO PORT',
  '0276' = '276 - Senff S.A. – Crédito, Financiamento e Investimento',
  '0278' = '278 - Genial Investimentos Corretora de Valores Mobiliários S.A.',
  '0279' = '279 - COOPERATIVA DE CREDITO RURAL DE PRIMAVERA DO LESTE',
  '0280' = '280 - Avista S.A. Crédito, Financiamento e Investimento',
  '0281' = '281 - Cooperativa de Crédito Rural Coopavel',
  '0283' = '283 - RB CAPITAL INVESTIMENTOS DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LIMITADA',
  '0285' = '285 - Frente Corretora de Câmbio Ltda.',
  '0286' = '286 - COOPERATIVA DE CRÉDITO RURAL DE OURO SULCREDI/OURO',
  '0288' = '288 - CAROL DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA.',
  '0289' = '289 - DECYSEO CORRETORA DE CAMBIO LTDA.',
  '0290' = '290 - Pagseguro Internet S.A. – PagBank',
  '0292' = '292 - BS2 Distribuidora de Títulos e Valores Mobiliários S.A.',
  '0293' = '293 - Lastro RDV Distribuidora de Títulos e Valores Mobiliários Ltda.',
  '0296' = '296 - VISION S.A. CORRETORA DE CAMBIO',
  '0298' = '298 - Vip’s Corretora de Câmbio Ltda.',
  '0299' = '299 - SOROCRED CRÉDITO, FINANCIAMENTO E INVESTIMENTO S.A.',
  '0300' = '300 - Banco de La Nacion Argentina',
  '0301' = '301 - BPP Instituição de Pagamento S.A.',
  '0306' = '306 - PORTOPAR DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA.',
  '0307' = '307 - Terra Investimentos Distribuidora de Títulos e Valores Mobiliários Ltda.',
  '0309' = '309 - CAMBIONET CORRETORA DE CÂMBIO LTDA.',
  '0310' = '310 - VORTX DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA.',
  '0315' = '315 - PI Distribuidora de Títulos e Valores Mobiliários S.A.',
  '0318' = '318 - Banco BMG S.A.',
  '0319' = '319 - OM DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA',
  '0320' = '320 - China Construction Bank (Brasil) Banco Múltiplo S.A.',
  '0321' = '321 - CREFAZ SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E A EMPRESA DE PEQUENO PORTE LT',
  '0322' = '322 - Cooperativa de Crédito Rural de Abelardo Luz – Sulcredi/Crediluz',
  '0323' = '323 - MERCADOPAGO.COM REPRESENTACOES LTDA.',
  '0325' = '325 - Órama Distribuidora de Títulos e Valores Mobiliários S.A.',
  '0326' = '326 - PARATI – CREDITO, FINANCIAMENTO E INVESTIMENTO S.A.',
  '0329' = '329 - QI Sociedade de Crédito Direto S.A.',
  '0330' = '330 - Banco Bari de Investimentos e Financiamentos S/A',
  '0331' = '331 - Fram Capital Distribuidora de Títulos e Valores Mobiliários S.A.',
  '0332' = '332 - Acesso Soluções de Pagamento S.A.',
  '0335' = '335 - Banco Digio S.A.',
  '0336' = '336 - Banco C6 S.A – C6 Bank',
  '0340' = '340 - Super Pagamentos e Administração de Meios Eletrônicos S.A.',
  '0341' = '341 - Itaú Unibanco S.A.',
  '0342' = '342 - Creditas Sociedade de Crédito Direto S.A.',
  '0343' = '343 - FFA SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE LTDA.',
  '0348' = '348 - Banco XP S.A.',
  '0349' = '349 - AMAGGI S.A. – CRÉDITO, FINANCIAMENTO E INVESTIMENTO',
  '0352' = '352 - TORO CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA',
  '0354' = '354 - NECTON INVESTIMENTOS S.A. CORRETORA DE VALORES MOBILIÁRIOS E COMMODITIES',
  '0355' = '355 - ÓTIMO SOCIEDADE DE CRÉDITO DIRETO S.A.',
  '0364' = '364 - GERENCIANET PAGAMENTOS DO BRASIL LTDA',
  '0365' = '365 - SOLIDUS S.A. CORRETORA DE CAMBIO E VALORES MOBILIARIOS',
  '0366' = '366 - Banco Société Générale Brasil S.A.',
  '0367' = '367 - VITREO DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.',
  '0368' = '368 - Banco Carrefour',
  '0370' = '370 - Banco Mizuho do Brasil S.A.',
  '0373' = '373 - UP.P SOCIEDADE DE EMPRÉSTIMO ENTRE PESSOAS S.A.',
  '0376' = '376 - Banco J. P. Morgan S.A.',
  '0380' = '380 - PicPay',
  '0389' = '389 - Banco Mercantil do Brasil S.A.',
  '0394' = '394 - Banco Bradesco Financiamentos S.A.',
  '0399' = '399 - Kirton Bank S.A. – Banco Múltiplo',
  '0412' = '412 - Banco Capital S.A.',
  '0422' = '422 - Banco Safra S.A.',
  '0456' = '456 - Banco MUFG Brasil S.A.',
  '0464' = '464 - Banco Sumitomo Mitsui Brasileiro S.A.',
  '0473' = '473 - Banco Caixa Geral – Brasil S.A.',
  '0477' = '477 - Citibank N.A.',
  '0479' = '479 - Banco ItauBank S.A',
  '0487' = '487 - Deutsche Bank S.A. – Banco Alemão',
  '0488' = '488 - JPMorgan Chase Bank',
  '0492' = '492 - ING Bank N.V.',
  '0495' = '495 - Banco de La Provincia de Buenos Aires',
  '0505' = '505 - Banco Credit Suisse (Brasil) S.A.',
  '0545' = '545 - SENSO CORRETORA DE CAMBIO E VALORES MOBILIARIOS S.A',
  '0600' = '600 - Banco Luso Brasileiro S.A.',
  '0604' = '604 - Banco Industrial do Brasil S.A.',
  '0610' = '610 - Banco VR S.A.',
  '0611' = '611 - Banco Paulista S.A.',
  '0612' = '612 - Banco Guanabara S.A.',
  '0613' = '613 - Omni Banco S.A.',
  '0623' = '623 - Banco PAN S.A.',
  '0626' = '626 - Banco Ficsa S.A.',
  '0630' = '630 - Banco Smartbank S.A.',
  '0633' = '633 - Banco Rendimento S.A.',
  '0634' = '634 - Banco Triângulo S.A.',
  '0637' = '637 - Banco Sofisa S.A.',
  '0643' = '643 - Banco Pine S.A.',
  '0652' = '652 - Itaú Unibanco Holding S.A.',
  '0653' = '653 - Banco Indusval S.A.',
  '0654' = '654 - Banco A.J.Renner S.A.',
  '0655' = '655 - Banco Votorantim S.A.',
  '0707' = '707 - Banco Daycoval S.A.',
  '0712' = '712 - Banco Ourinvest S.A.',
  '0739' = '739 - Banco Cetelem S.A.',
  '0741' = '741 - Banco Ribeirão Preto S.A.',
  '0743' = '743 - Banco Semear S.A.',
  '0745' = '745 - Banco Citibank S.A.',
  '0746' = '746 - Banco Modal S.A.',
  '0747' = '747 - Banco Rabobank International Brasil S.A.',
  '0748' = '748 - Banco Cooperativo Sicredi S.A.',
  '0751' = '751 - Scotiabank Brasil S.A. Banco Múltiplo',
  '0752' = '752 - Banco BNP Paribas Brasil S.A.',
  '0753' = '753 - Novo Banco Continental S.A. – Banco Múltiplo',
  '0754' = '754 - Banco Sistema S.A.',
  '0755' = '755 - Bank of America Merrill Lynch Banco Múltiplo S.A.',
  '0756' = '756 - Banco Cooperativo do Brasil S.A. – BANCOOB',
  '0757' = '757 - Banco KEB HANA do Brasil S.A.',
}
